name: 'Yamllint GitHub Actions'
on:
  - pull_request
permissions: read-all
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@fdef6bc189425ecc84cc4543b2674566c0827053
        with:
          yamllint_file_or_dir: '.'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
